package model.service;

import javax.servlet.http.HttpSession;
import javax.faces.context.ExternalContext;
import javax.faces.context.FacesContext;

import model.service.common.AppModule;

import model.view.MonthSearchVOImpl;
import model.view.SpLineCapacityHVOImpl;

import oracle.jbo.server.ApplicationModuleImpl;
import oracle.jbo.server.ViewLinkImpl;
import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sun Jun 05 16:21:20 BDT 2022
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class AppModuleImpl extends ApplicationModuleImpl implements AppModule {
    /**
     * This is the default constructor (do not remove).
     */
    public AppModuleImpl() {
    }
    public void setSessionValues(String orgId, String userId, String respId,
                                 String respApplId) {  
        
    //    System.out.println("====================  set session values    ================================");

    //       System.out.println(" orgId "+ orgId  + "  data type  "+ orgId.getClass().getName());
    //
           orgId = "340";
           userId = "5219";
        FacesContext fctx = FacesContext.getCurrentInstance();
        ExternalContext ectx = fctx.getExternalContext();
        HttpSession userSession = (HttpSession)ectx.getSession(false);

        if (orgId != null) {
            userSession.setAttribute("orgId", orgId);
        }

        if (userId != null) {
            userSession.setAttribute("userId", userId);
        }

        if (respId != null) {
            userSession.setAttribute("respId", respId);
        }

        if (respApplId != null) {
            userSession.setAttribute("respApplId", respApplId);
        }         
         
      }


    /**
     * Container's getter for OrgVO1.
     * @return OrgVO1
     */
    public ViewObjectImpl getOrgVO1() {
        return (ViewObjectImpl)findViewObject("OrgVO1");
    }


    /**
     * Container's getter for SpLineCapacityHVO1.
     * @return SpLineCapacityHVO1
     */
    public ViewObjectImpl getSpLineCapacityHVO1() {
        return (ViewObjectImpl)findViewObject("SpLineCapacityHVO1");
    }

    /**
     * Container's getter for OrgVO_vs_SpLineCapacityH_VL1.
     * @return OrgVO_vs_SpLineCapacityH_VL1
     */
    public ViewLinkImpl getOrgVO_vs_SpLineCapacityH_VL1() {
        return (ViewLinkImpl)findViewLink("OrgVO_vs_SpLineCapacityH_VL1");
    }

    /**
     * Container's getter for SpLineCapacityLVO1.
     * @return SpLineCapacityLVO1
     */
    public ViewObjectImpl getSpLineCapacityLVO1() {
        return (ViewObjectImpl)findViewObject("SpLineCapacityLVO1");
    }

    /**
     * Container's getter for OrgVO_vs_SpLineCapacityL_VL1.
     * @return OrgVO_vs_SpLineCapacityL_VL1
     */
    public ViewLinkImpl getOrgVO_vs_SpLineCapacityL_VL1() {
        return (ViewLinkImpl)findViewLink("OrgVO_vs_SpLineCapacityL_VL1");
    }


    /**
     * Container's getter for SpLineDefaultWhVO1.
     * @return SpLineDefaultWhVO1
     */
    public ViewObjectImpl getSpLineDefaultWhVO1() {
        return (ViewObjectImpl)findViewObject("SpLineDefaultWhVO1");
    }

    /**
     * Container's getter for OrgVO_vs_SpLineDefaultWhVO_VL1.
     * @return OrgVO_vs_SpLineDefaultWhVO_VL1
     */
    public ViewLinkImpl getOrgVO_vs_SpLineDefaultWhVO_VL1() {
        return (ViewLinkImpl)findViewLink("OrgVO_vs_SpLineDefaultWhVO_VL1");
    }

    /**
     * Container's getter for MonthSearchVO1.
     * @return MonthSearchVO1
     */
    public MonthSearchVOImpl getMonthSearchVO1() {
        return (MonthSearchVOImpl)findViewObject("MonthSearchVO1");
    }

    /**
     * Container's getter for SpCalendarHVO1.
     * @return SpCalendarHVO1
     */
    public ViewObjectImpl getSpCalendarHVO1() {
        return (ViewObjectImpl)findViewObject("SpCalendarHVO1");
    }

    /**
     * Container's getter for MonthSearchVO_Vs_SpCalendarHVO_VL1.
     * @return MonthSearchVO_Vs_SpCalendarHVO_VL1
     */
    public ViewLinkImpl getMonthSearchVO_Vs_SpCalendarHVO_VL1() {
        return (ViewLinkImpl)findViewLink("MonthSearchVO_Vs_SpCalendarHVO_VL1");
    }

    /**
     * Container's getter for MonthWiseDailyWorkingHourVO1.
     * @return MonthWiseDailyWorkingHourVO1
     */
    public ViewObjectImpl getMonthWiseDailyWorkingHourVO1() {
        return (ViewObjectImpl)findViewObject("MonthWiseDailyWorkingHourVO1");
    }

    /**
     * Container's getter for SpCalendarHVO_Vs_MonthWiseDailyWorkingHourVO_VL1.
     * @return SpCalendarHVO_Vs_MonthWiseDailyWorkingHourVO_VL1
     */
    public ViewLinkImpl getSpCalendarHVO_Vs_MonthWiseDailyWorkingHourVO_VL1() {
        return (ViewLinkImpl)findViewLink("SpCalendarHVO_Vs_MonthWiseDailyWorkingHourVO_VL1");
    }
}
