package model.view;

import oracle.jbo.Row;
import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sun Jun 12 12:36:13 BDT 2022
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class SpCalendarHVOImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public SpCalendarHVOImpl() {
    }
    @Override
    public Row getCurrentRow() {
       if(super.getCurrentRow() == null) {       
           
           super.setCurrentRow(super.first());
       
       }
       
       return super.getCurrentRow();
       
    }
    
}
