package model.view;

import oracle.jbo.Row;
import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Jun 06 13:19:06 BDT 2022
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class SpLineCapacityHVOImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public SpLineCapacityHVOImpl() {
    }
    
    @Override
          public void insertRow(Row row) {
        
          //    this.insertRowAtRangeIndex(1, row);
              Row firstRow = this.first();
              if (firstRow != null) {
                  //insert new row at the end and make it current
                  int indx = this.getRangeIndexOf(firstRow) ;
                  this.insertRowAtRangeIndex(indx, row);
              } else {
                  super.insertRow(row);
              }
          }
}
